# Generated by Django 5.1.6 on 2025-02-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('imagem_url', models.URLField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_sem_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentual_desconto', models.IntegerField(blank=True, null=True)),
                ('parcelamento', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField()),
                ('tipo_entrega', models.CharField(choices=[('Full', 'Full'), ('Normal', 'Normal')], max_length=50)),
                ('frete_gratis', models.BooleanField(default=False)),
            ],
        ),
    ]
