# Generated by Django 5.1.6 on 2025-02-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='link',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
