# Generated by Django 5.1.6 on 2025-02-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_alter_produto_imagem_url_alter_produto_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='produto',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=500),
        ),
    ]
